### ISSUE TITLE
Customise the text on the output

### ISSUE THREAD

**Issue by pete284** [ggagnon76/ipdip#3]
A great little module, I have been customising the output to chat by editing the ipdip.js file, however, on a new update I have to remember to re-edit the file.

It would be nice to have a setting in configure settings to set different text for the output to chat.

**Comment by ggagnon76** [comment]
To be honest, I was expecting this request if the module gained any kind of popularity.
Summer is a busy time for me.  I will definitely attempt to implement a customizable chat output when I update/rework the module.
